name: run-cdk-diff
author: ibuki0212job@gmail.com
description: run `cdk diff` command
inputs:
  infraDir:
    description: cdk top directory
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
    - name: cache node_modules
      id: node_modules_cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ matrix.os }}-${{ hashFiles('./package-lock.json') }}
    - name: install dependency
      shell: bash
      run: |
        cd ${{ inputs.infraDir }}
        npm install --legacy-peer-deps
    - name: run snapshot test
      shell: bash
      run: |
        cd ${{ inputs.infraDir }}
        npm test